//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Interface/CharacterControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterControls"",
    ""maps"": [
        {
            ""name"": ""character"",
            ""id"": ""a3170022-aa82-4b0d-95ac-9e9178efdfbc"",
            ""actions"": [
                {
                    ""name"": ""aim"",
                    ""type"": ""Value"",
                    ""id"": ""7071446c-b52b-4cab-b22b-0abd99c27ef6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""593ab85e-b581-426f-af0c-3a13e439f93f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""running"",
                    ""type"": ""Value"",
                    ""id"": ""a19ed657-3f14-4501-9aac-6aef62a9dbd5"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""dash"",
                    ""type"": ""PassThrough"",
                    ""id"": ""03841b82-074c-4841-af00-16aa08a8a2ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""block"",
                    ""type"": ""Button"",
                    ""id"": ""6799233d-eda8-4a5c-a64d-cf710a687472"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shield"",
                    ""type"": ""Button"",
                    ""id"": ""43efeb36-47c0-4ffc-8969-7f7968afa0d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""light1"",
                    ""type"": ""Button"",
                    ""id"": ""6efbe99c-c453-4ef7-baaf-1eba0682fa37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""light2"",
                    ""type"": ""Button"",
                    ""id"": ""c8e7466a-1c5c-4cd0-98e3-31a459176f26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""boostedLight"",
                    ""type"": ""Button"",
                    ""id"": ""4e495e9e-6745-4925-8d77-c3e0181c2533"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""medium1"",
                    ""type"": ""Button"",
                    ""id"": ""ab2900fa-aeb8-440d-b6be-963dfcf91056"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""medium2"",
                    ""type"": ""Button"",
                    ""id"": ""d04cbfee-619d-44fc-8638-c0479e5d113a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""boostedMedium"",
                    ""type"": ""Button"",
                    ""id"": ""f0363c49-7e1c-4105-b161-bc9aea3cd4b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""heavy1"",
                    ""type"": ""Button"",
                    ""id"": ""5a69b126-bb2f-4369-96e4-ae16f779b7db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""heavy2"",
                    ""type"": ""Button"",
                    ""id"": ""503c263f-e657-4bc3-b587-c3f10007c43a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""boostedHeavy"",
                    ""type"": ""Button"",
                    ""id"": ""7e44cf9b-7864-40c6-8035-ffcb250a5541"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""throw1"",
                    ""type"": ""Button"",
                    ""id"": ""cd4e2a1f-0f90-456f-97e9-51fb88996b76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""throw2"",
                    ""type"": ""Button"",
                    ""id"": ""cef4c676-3f7d-4799-b498-bcb854841719"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""boostedThrow"",
                    ""type"": ""Button"",
                    ""id"": ""faca5904-be86-4bbe-acde-c5f865e05f15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ability1"",
                    ""type"": ""Button"",
                    ""id"": ""ca228c90-9d79-4782-830a-c1d545e07dc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ability2"",
                    ""type"": ""Button"",
                    ""id"": ""37c2848a-7965-49a0-82a1-69d9c9a1f8cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ability3"",
                    ""type"": ""Button"",
                    ""id"": ""5f3af129-6bd7-4902-abb4-026dfc9373c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ability4"",
                    ""type"": ""Button"",
                    ""id"": ""dc13de7b-336a-421f-8064-ac2b260bcba3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""special1"",
                    ""type"": ""Button"",
                    ""id"": ""ad3ad947-20e0-40a5-ac4a-b57b1cd5f175"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""special2"",
                    ""type"": ""Button"",
                    ""id"": ""5c04025d-4c8e-4556-a231-f22401670469"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""a4c3711a-0f84-4516-9c92-b054a662ffbe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8cfb5123-ad66-425e-9e17-c599b1e1a796"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""light1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6b633829-3731-40c1-9aae-3a36de276886"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2865cbad-2092-4f2a-b62a-75bab3f42206"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""de6393e1-b721-47ae-b7aa-6b92ad320fb9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0431a7fe-a653-4a8e-99ed-c6bf91169dc6"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bffe3d1d-008c-4778-b87a-b8ae499e8f1e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8d23d421-599b-4a0a-bd8f-2777818e8f14"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""717b62a6-f26b-4ee9-ba86-b6115742da17"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""c71358eb-0060-4817-b993-06ea8db4d5a7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4d1d5722-c212-4572-b838-08e3ddf04b71"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""02db7937-eee1-4165-ad8c-389ba9c7bfeb"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0ac5f213-f15d-42ca-8419-ddb4bd0dfec7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""be347fe6-221e-4cb1-838d-ace97bd03480"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""throw2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7bf3f69e-6089-4444-b1b7-e66394ce58b7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ability1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc1480b0-0b12-4eb8-b466-99ccc24bf794"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ability2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1bff09e-5368-47b3-8369-63387b63cbe4"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ability3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66c67367-3003-4da9-ba71-db3a4b1d3d8a"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ability4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02ec5e36-e7bd-4392-82f5-220366fdf7ae"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""676e2df3-15eb-4952-a404-a9a5a431ab50"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""d06e8647-70af-4679-ab6b-88fedfd0d11d"",
                    ""path"": ""ButtonWithOneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""250e04b2-195c-4440-a97e-7826cb4bd674"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""61c051ab-0ba7-4d6a-8830-5a5c70c960b0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""76f96e17-7442-46f8-8512-b557e10cc3e2"",
                    ""path"": ""ButtonWithOneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""1a649a60-cd11-40ce-bb2a-11bfe136690d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""166b5ce3-4b77-4373-98c6-0d66ab339c67"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""581e2e5c-e670-4a6f-b20f-664ea0e77f72"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c38e173-ba53-482f-9dfd-2116498c1426"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""0a463c49-b4aa-4585-8231-67be2e27470c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedThrow"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5447c178-e92e-445f-9323-bccac1dfb225"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""85c42796-f278-4159-90ca-4c58ce1bcf2f"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2f28835d-e488-4c39-b977-046ce0baafe1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a3986093-3a30-4d80-ad24-06fe7c1124f6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5cad4734-8190-47dd-9717-edd940534e38"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""79f00a4c-61c8-454a-a410-ac1b94d34035"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1fe25519-afc3-41cb-98e9-05b5e064905d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6c82a423-5fdf-4376-8087-8e680ece2064"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""475b0d0d-6481-434b-bf08-111a02bbfbb9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4cba9f21-ceeb-4119-988a-9f14346b362f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""9f6bae7f-a797-44da-a3ed-6a4197dc87c6"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2a0ae7c2-be64-4b8c-b853-49d7e01ff440"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""light2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf20fb7a-7adf-4b31-ba3f-d28500e5a363"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ef4fa377-bc54-4544-b513-dcd90e99c670"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1720ff93-7970-4da6-88d1-7aca9d72f731"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""131b0151-f767-43e2-a930-ee625078cb81"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""medium2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""38c8443e-2306-47a6-833d-d13d1795c089"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedMedium"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""867d579e-48f3-4d3b-97be-25cfc051b324"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedMedium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d795e94a-4746-4238-a803-a3e1c9af40be"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedMedium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""bbb2992c-64c6-4f03-a8ef-2cc9e039d18c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8bb2d328-06c0-481e-a2db-6fedb4a36747"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""22fccc22-5e14-480d-8be0-151cc2046ff6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""18114b79-837c-4dff-b1b6-c4903da2f027"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9495dbb5-0e77-448c-b2c4-c1406885d1d5"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b5188584-214e-43a4-b775-504700248981"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""heavy2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""b6a99ebe-9702-45c2-93a5-06d2bbf0e27a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedHeavy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ac1ef15f-658c-4a00-87be-dff7000a679f"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6a9eaece-aa4f-47c4-96da-9a1412e69f75"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boostedHeavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""625d659d-3d22-4ee3-92b3-adb729da7ac7"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d9bcc0cd-03c3-4ebd-bdb7-28f5e785e4da"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""553ea218-739a-44e7-a314-b1effaece0df"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""special2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0f660273-1f8c-4b3d-97d8-d79ed7fa45ae"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d7c51ac-eadd-4fc1-bae5-011688ce73ea"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b4d105cd-ca13-4649-863c-36972f4d07b1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a1fada33-ca86-487a-bd8c-de94ee950af8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2f2a2ce6-6cc8-44df-9561-051e48cc2e2c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""99e1aeb5-46db-441d-813a-f23df99fe343"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""38a9da30-48e3-4a01-acc5-4f4f70cb4061"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // character
        m_character = asset.FindActionMap("character", throwIfNotFound: true);
        m_character_aim = m_character.FindAction("aim", throwIfNotFound: true);
        m_character_movement = m_character.FindAction("movement", throwIfNotFound: true);
        m_character_running = m_character.FindAction("running", throwIfNotFound: true);
        m_character_dash = m_character.FindAction("dash", throwIfNotFound: true);
        m_character_block = m_character.FindAction("block", throwIfNotFound: true);
        m_character_shield = m_character.FindAction("shield", throwIfNotFound: true);
        m_character_light1 = m_character.FindAction("light1", throwIfNotFound: true);
        m_character_light2 = m_character.FindAction("light2", throwIfNotFound: true);
        m_character_boostedLight = m_character.FindAction("boostedLight", throwIfNotFound: true);
        m_character_medium1 = m_character.FindAction("medium1", throwIfNotFound: true);
        m_character_medium2 = m_character.FindAction("medium2", throwIfNotFound: true);
        m_character_boostedMedium = m_character.FindAction("boostedMedium", throwIfNotFound: true);
        m_character_heavy1 = m_character.FindAction("heavy1", throwIfNotFound: true);
        m_character_heavy2 = m_character.FindAction("heavy2", throwIfNotFound: true);
        m_character_boostedHeavy = m_character.FindAction("boostedHeavy", throwIfNotFound: true);
        m_character_throw1 = m_character.FindAction("throw1", throwIfNotFound: true);
        m_character_throw2 = m_character.FindAction("throw2", throwIfNotFound: true);
        m_character_boostedThrow = m_character.FindAction("boostedThrow", throwIfNotFound: true);
        m_character_ability1 = m_character.FindAction("ability1", throwIfNotFound: true);
        m_character_ability2 = m_character.FindAction("ability2", throwIfNotFound: true);
        m_character_ability3 = m_character.FindAction("ability3", throwIfNotFound: true);
        m_character_ability4 = m_character.FindAction("ability4", throwIfNotFound: true);
        m_character_special1 = m_character.FindAction("special1", throwIfNotFound: true);
        m_character_special2 = m_character.FindAction("special2", throwIfNotFound: true);
        m_character_ultimate = m_character.FindAction("ultimate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // character
    private readonly InputActionMap m_character;
    private List<ICharacterActions> m_CharacterActionsCallbackInterfaces = new List<ICharacterActions>();
    private readonly InputAction m_character_aim;
    private readonly InputAction m_character_movement;
    private readonly InputAction m_character_running;
    private readonly InputAction m_character_dash;
    private readonly InputAction m_character_block;
    private readonly InputAction m_character_shield;
    private readonly InputAction m_character_light1;
    private readonly InputAction m_character_light2;
    private readonly InputAction m_character_boostedLight;
    private readonly InputAction m_character_medium1;
    private readonly InputAction m_character_medium2;
    private readonly InputAction m_character_boostedMedium;
    private readonly InputAction m_character_heavy1;
    private readonly InputAction m_character_heavy2;
    private readonly InputAction m_character_boostedHeavy;
    private readonly InputAction m_character_throw1;
    private readonly InputAction m_character_throw2;
    private readonly InputAction m_character_boostedThrow;
    private readonly InputAction m_character_ability1;
    private readonly InputAction m_character_ability2;
    private readonly InputAction m_character_ability3;
    private readonly InputAction m_character_ability4;
    private readonly InputAction m_character_special1;
    private readonly InputAction m_character_special2;
    private readonly InputAction m_character_ultimate;
    public struct CharacterActions
    {
        private @CharacterControls m_Wrapper;
        public CharacterActions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @aim => m_Wrapper.m_character_aim;
        public InputAction @movement => m_Wrapper.m_character_movement;
        public InputAction @running => m_Wrapper.m_character_running;
        public InputAction @dash => m_Wrapper.m_character_dash;
        public InputAction @block => m_Wrapper.m_character_block;
        public InputAction @shield => m_Wrapper.m_character_shield;
        public InputAction @light1 => m_Wrapper.m_character_light1;
        public InputAction @light2 => m_Wrapper.m_character_light2;
        public InputAction @boostedLight => m_Wrapper.m_character_boostedLight;
        public InputAction @medium1 => m_Wrapper.m_character_medium1;
        public InputAction @medium2 => m_Wrapper.m_character_medium2;
        public InputAction @boostedMedium => m_Wrapper.m_character_boostedMedium;
        public InputAction @heavy1 => m_Wrapper.m_character_heavy1;
        public InputAction @heavy2 => m_Wrapper.m_character_heavy2;
        public InputAction @boostedHeavy => m_Wrapper.m_character_boostedHeavy;
        public InputAction @throw1 => m_Wrapper.m_character_throw1;
        public InputAction @throw2 => m_Wrapper.m_character_throw2;
        public InputAction @boostedThrow => m_Wrapper.m_character_boostedThrow;
        public InputAction @ability1 => m_Wrapper.m_character_ability1;
        public InputAction @ability2 => m_Wrapper.m_character_ability2;
        public InputAction @ability3 => m_Wrapper.m_character_ability3;
        public InputAction @ability4 => m_Wrapper.m_character_ability4;
        public InputAction @special1 => m_Wrapper.m_character_special1;
        public InputAction @special2 => m_Wrapper.m_character_special2;
        public InputAction @ultimate => m_Wrapper.m_character_ultimate;
        public InputActionMap Get() { return m_Wrapper.m_character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Add(instance);
            @aim.started += instance.OnAim;
            @aim.performed += instance.OnAim;
            @aim.canceled += instance.OnAim;
            @movement.started += instance.OnMovement;
            @movement.performed += instance.OnMovement;
            @movement.canceled += instance.OnMovement;
            @running.started += instance.OnRunning;
            @running.performed += instance.OnRunning;
            @running.canceled += instance.OnRunning;
            @dash.started += instance.OnDash;
            @dash.performed += instance.OnDash;
            @dash.canceled += instance.OnDash;
            @block.started += instance.OnBlock;
            @block.performed += instance.OnBlock;
            @block.canceled += instance.OnBlock;
            @shield.started += instance.OnShield;
            @shield.performed += instance.OnShield;
            @shield.canceled += instance.OnShield;
            @light1.started += instance.OnLight1;
            @light1.performed += instance.OnLight1;
            @light1.canceled += instance.OnLight1;
            @light2.started += instance.OnLight2;
            @light2.performed += instance.OnLight2;
            @light2.canceled += instance.OnLight2;
            @boostedLight.started += instance.OnBoostedLight;
            @boostedLight.performed += instance.OnBoostedLight;
            @boostedLight.canceled += instance.OnBoostedLight;
            @medium1.started += instance.OnMedium1;
            @medium1.performed += instance.OnMedium1;
            @medium1.canceled += instance.OnMedium1;
            @medium2.started += instance.OnMedium2;
            @medium2.performed += instance.OnMedium2;
            @medium2.canceled += instance.OnMedium2;
            @boostedMedium.started += instance.OnBoostedMedium;
            @boostedMedium.performed += instance.OnBoostedMedium;
            @boostedMedium.canceled += instance.OnBoostedMedium;
            @heavy1.started += instance.OnHeavy1;
            @heavy1.performed += instance.OnHeavy1;
            @heavy1.canceled += instance.OnHeavy1;
            @heavy2.started += instance.OnHeavy2;
            @heavy2.performed += instance.OnHeavy2;
            @heavy2.canceled += instance.OnHeavy2;
            @boostedHeavy.started += instance.OnBoostedHeavy;
            @boostedHeavy.performed += instance.OnBoostedHeavy;
            @boostedHeavy.canceled += instance.OnBoostedHeavy;
            @throw1.started += instance.OnThrow1;
            @throw1.performed += instance.OnThrow1;
            @throw1.canceled += instance.OnThrow1;
            @throw2.started += instance.OnThrow2;
            @throw2.performed += instance.OnThrow2;
            @throw2.canceled += instance.OnThrow2;
            @boostedThrow.started += instance.OnBoostedThrow;
            @boostedThrow.performed += instance.OnBoostedThrow;
            @boostedThrow.canceled += instance.OnBoostedThrow;
            @ability1.started += instance.OnAbility1;
            @ability1.performed += instance.OnAbility1;
            @ability1.canceled += instance.OnAbility1;
            @ability2.started += instance.OnAbility2;
            @ability2.performed += instance.OnAbility2;
            @ability2.canceled += instance.OnAbility2;
            @ability3.started += instance.OnAbility3;
            @ability3.performed += instance.OnAbility3;
            @ability3.canceled += instance.OnAbility3;
            @ability4.started += instance.OnAbility4;
            @ability4.performed += instance.OnAbility4;
            @ability4.canceled += instance.OnAbility4;
            @special1.started += instance.OnSpecial1;
            @special1.performed += instance.OnSpecial1;
            @special1.canceled += instance.OnSpecial1;
            @special2.started += instance.OnSpecial2;
            @special2.performed += instance.OnSpecial2;
            @special2.canceled += instance.OnSpecial2;
            @ultimate.started += instance.OnUltimate;
            @ultimate.performed += instance.OnUltimate;
            @ultimate.canceled += instance.OnUltimate;
        }

        private void UnregisterCallbacks(ICharacterActions instance)
        {
            @aim.started -= instance.OnAim;
            @aim.performed -= instance.OnAim;
            @aim.canceled -= instance.OnAim;
            @movement.started -= instance.OnMovement;
            @movement.performed -= instance.OnMovement;
            @movement.canceled -= instance.OnMovement;
            @running.started -= instance.OnRunning;
            @running.performed -= instance.OnRunning;
            @running.canceled -= instance.OnRunning;
            @dash.started -= instance.OnDash;
            @dash.performed -= instance.OnDash;
            @dash.canceled -= instance.OnDash;
            @block.started -= instance.OnBlock;
            @block.performed -= instance.OnBlock;
            @block.canceled -= instance.OnBlock;
            @shield.started -= instance.OnShield;
            @shield.performed -= instance.OnShield;
            @shield.canceled -= instance.OnShield;
            @light1.started -= instance.OnLight1;
            @light1.performed -= instance.OnLight1;
            @light1.canceled -= instance.OnLight1;
            @light2.started -= instance.OnLight2;
            @light2.performed -= instance.OnLight2;
            @light2.canceled -= instance.OnLight2;
            @boostedLight.started -= instance.OnBoostedLight;
            @boostedLight.performed -= instance.OnBoostedLight;
            @boostedLight.canceled -= instance.OnBoostedLight;
            @medium1.started -= instance.OnMedium1;
            @medium1.performed -= instance.OnMedium1;
            @medium1.canceled -= instance.OnMedium1;
            @medium2.started -= instance.OnMedium2;
            @medium2.performed -= instance.OnMedium2;
            @medium2.canceled -= instance.OnMedium2;
            @boostedMedium.started -= instance.OnBoostedMedium;
            @boostedMedium.performed -= instance.OnBoostedMedium;
            @boostedMedium.canceled -= instance.OnBoostedMedium;
            @heavy1.started -= instance.OnHeavy1;
            @heavy1.performed -= instance.OnHeavy1;
            @heavy1.canceled -= instance.OnHeavy1;
            @heavy2.started -= instance.OnHeavy2;
            @heavy2.performed -= instance.OnHeavy2;
            @heavy2.canceled -= instance.OnHeavy2;
            @boostedHeavy.started -= instance.OnBoostedHeavy;
            @boostedHeavy.performed -= instance.OnBoostedHeavy;
            @boostedHeavy.canceled -= instance.OnBoostedHeavy;
            @throw1.started -= instance.OnThrow1;
            @throw1.performed -= instance.OnThrow1;
            @throw1.canceled -= instance.OnThrow1;
            @throw2.started -= instance.OnThrow2;
            @throw2.performed -= instance.OnThrow2;
            @throw2.canceled -= instance.OnThrow2;
            @boostedThrow.started -= instance.OnBoostedThrow;
            @boostedThrow.performed -= instance.OnBoostedThrow;
            @boostedThrow.canceled -= instance.OnBoostedThrow;
            @ability1.started -= instance.OnAbility1;
            @ability1.performed -= instance.OnAbility1;
            @ability1.canceled -= instance.OnAbility1;
            @ability2.started -= instance.OnAbility2;
            @ability2.performed -= instance.OnAbility2;
            @ability2.canceled -= instance.OnAbility2;
            @ability3.started -= instance.OnAbility3;
            @ability3.performed -= instance.OnAbility3;
            @ability3.canceled -= instance.OnAbility3;
            @ability4.started -= instance.OnAbility4;
            @ability4.performed -= instance.OnAbility4;
            @ability4.canceled -= instance.OnAbility4;
            @special1.started -= instance.OnSpecial1;
            @special1.performed -= instance.OnSpecial1;
            @special1.canceled -= instance.OnSpecial1;
            @special2.started -= instance.OnSpecial2;
            @special2.performed -= instance.OnSpecial2;
            @special2.canceled -= instance.OnSpecial2;
            @ultimate.started -= instance.OnUltimate;
            @ultimate.performed -= instance.OnUltimate;
            @ultimate.canceled -= instance.OnUltimate;
        }

        public void RemoveCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterActions @character => new CharacterActions(this);
    public interface ICharacterActions
    {
        void OnAim(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnRunning(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnShield(InputAction.CallbackContext context);
        void OnLight1(InputAction.CallbackContext context);
        void OnLight2(InputAction.CallbackContext context);
        void OnBoostedLight(InputAction.CallbackContext context);
        void OnMedium1(InputAction.CallbackContext context);
        void OnMedium2(InputAction.CallbackContext context);
        void OnBoostedMedium(InputAction.CallbackContext context);
        void OnHeavy1(InputAction.CallbackContext context);
        void OnHeavy2(InputAction.CallbackContext context);
        void OnBoostedHeavy(InputAction.CallbackContext context);
        void OnThrow1(InputAction.CallbackContext context);
        void OnThrow2(InputAction.CallbackContext context);
        void OnBoostedThrow(InputAction.CallbackContext context);
        void OnAbility1(InputAction.CallbackContext context);
        void OnAbility2(InputAction.CallbackContext context);
        void OnAbility3(InputAction.CallbackContext context);
        void OnAbility4(InputAction.CallbackContext context);
        void OnSpecial1(InputAction.CallbackContext context);
        void OnSpecial2(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
    }
}
